CREATE TABLE IF NOT EXISTS public.tb_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT tb_user_pkey PRIMARY KEY (id),
    CONSTRAINT uk4vih17mube9j7cqyjlfbcrk4m UNIQUE (email)
    );