CREATE TABLE IF NOT EXISTS public.tb_order
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    moment timestamp(6) with time zone,
                            order_status integer,
                            client_id bigint,
                            CONSTRAINT tb_order_pkey PRIMARY KEY (id)
    );